### ISSUE TITLE
Problem when i throw him

### ISSUE THREAD

**Issue by guigui57500** [Oskang09/CrackshotBuilder#11]
When i throw him there is a TTPHelper window wich appears: 
![help](https://cloud.githubusercontent.com/assets/21359426/23096724/a4a1250c-f622-11e6-940e-061966cfbbc1.PNG)

How to solve this problem ?
Sorry for my bad english i'm french :)

**Comment by Oskang09** [comment]
Fixed on dev5.2 version

**Comment by guigui57500** [comment]
Thanks !
